# Generated by Django 4.2.3 on 2023-07-26 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Title')),
                ('job_designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation')),
                ('work_experience', models.CharField(blank=True, max_length=100, null=True, verbose_name='5+ Years')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('description', froala_editor.fields.FroalaField()),
                ('profile_image', models.ImageField(upload_to='profile')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
