# Generated by Django 4.2.3 on 2023-07-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_membersmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersmodel',
            name='work_experience',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Experience'),
        ),
    ]
