# Generated by Django 4.2.3 on 2023-07-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_membersmodel_work_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersmodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
