# Generated by Django 4.2.3 on 2023-07-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_membersmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersmodel',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
