# Generated by Django 4.2.3 on 2023-07-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_servicesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
